source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3'
gem 'memcache-client'

gem "rails_helpers_fix"

gem 'otwtranslation', :path => '../'

group :development, :test do
  gem "rspec-rails", "~> 2.5.0"
  gem "cucumber-rails", "~> 0.3.2"
  gem "capybara", "~> 0.4.1.2"
  gem "launchy"
end

