source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3'
gem 'memcache-client'
gem 'jquery-rails'
gem 'sanitize'
gem 'resque', '>=1.14.0'
gem 'resque_mailer'

gem "rails_helpers_fix"

gem 'otwtranslation', :path => '../'

gem 'authlogic',
  :git     => 'git://github.com/odorcicd/authlogic.git',
  :branch  => 'rails3',
  :require => 'authlogic'

gem 'permit_yo'

#gem 'will_paginate', '3.0.pre'
gem 'will_paginate',
  :git     => 'git://github.com/huerlisi/will_paginate.git',
  :branch  => 'rails3',
  :require => 'will_paginate'


group :development, :test do
  gem "rspec-rails"
  gem "cucumber-rails"
  gem "capybara"
  gem "launchy"
  gem "factory_girl"
  gem "webrat"
  gem "database_cleaner"
  #gem "akephalos"
  gem "selenium-webdriver"
  gem "pickle"
  gem "escape_utils"
end

