source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3'
gem 'memcache-client'
gem 'jquery-rails'

gem "rails_helpers_fix"

gem 'otwtranslation', :path => '../'

gem 'authlogic',
  :git     => 'git://github.com/odorcicd/authlogic.git',
  :branch  => 'rails3',
  :require => 'authlogic'

gem 'permit_yo'

group :development, :test do
  gem "rspec-rails", "~> 2.5.0"
  gem "cucumber-rails", "~> 0.3.2"
  gem "capybara", "~> 0.4.1.2"
  gem "launchy"
  gem "factory_girl"
  gem "webrat"
  gem "database_cleaner"
  gem "akephalos"
  gem "selenium-webdriver"
end

